### ISSUE TITLE
Carousel: Pager Doesn't Center on IE When Window is Small

### ISSUE THREAD

**Issue by Nicholas-Westby** [rhythmagency/rhythmagency.github.io#2]
http://rhythmagency.github.io/reference/galleries/carousel-1/

When the window width is small, the pager no longer centers and seems to cause a horizontal scrollbar:

![pager](https://cloud.githubusercontent.com/assets/5933222/6717972/7cec7e2e-cd6d-11e4-90f3-2422d2689636.png)

This only seems to be a problem with Internet Explorer (noticed on IE11).

**Comment by Brian-Lee-at-Rhythm** [comment]
Try refreshing the page, after resizing the window. I was on Windows 8 > IE10 and noticed the same issue. But a simple refresh seem to fix it. 

You can also achieve the same "fix" if you open up the inspector and uncheck/re-check the position: relative; set on the carousel nav (which is how I knew that a refresh would likely do the trick)

**Comment by Nicholas-Westby** [comment]
Yep, I noticed that as well. Since resizing the window to a smaller width isn't common on IE, I just fixed the scrollbar and am leaving the off-center pager alone: https://github.com/rhythmagency/rhythmagency.github.io/commit/78cfcd735a0800a3023bec6de7205bb683f132ac
